export const cargoSoonTrackingRecords = [
  {
    id: 'cargosoon-sea-ddp-in-transit',
    source: 'cargosoon_order',
    numberType: 'cargosoon_order',
    searchKeys: ['CSO-DDP-SEA-1001', 'SHP-SZLA-1001', 'REF-AMZ-LAX-1001'],
    displayNumber: 'CSO-DDP-SEA-1001',
    shipmentNumber: 'SHP-SZLA-1001',
    customerReference: 'REF-AMZ-LAX-1001',
    status: 'in_transit',
    statusLabel: 'In transit',
    carrier: 'CargoSoon Sea DDP',
    service: 'Sea DDP door-to-door',
    origin: 'Shenzhen warehouse, China',
    destination: 'Los Angeles, CA, United States',
    etd: 'Jun 8, 2026',
    eta: 'Jul 9, 2026',
    latestUpdate: 'Loaded on vessel. The shipment is moving to the port of discharge.',
    route: ['Shenzhen', 'Yantian Port', 'Los Angeles', 'Door delivery'],
    events: [
      {
        time: 'Jun 16, 2026 09:30',
        location: 'South China Sea',
        title: 'Vessel departure confirmed',
        description: 'Container is on the ocean leg to the United States.',
      },
      {
        time: 'Jun 13, 2026 18:20',
        location: 'Yantian Port, China',
        title: 'Loaded on vessel',
        description: 'Export handover has been completed.',
      },
      {
        time: 'Jun 10, 2026 15:40',
        location: 'Shenzhen warehouse, China',
        title: 'Cargo consolidated',
        description: 'Cartons were measured, labeled, and prepared for export.',
      },
      {
        time: 'Jun 8, 2026 10:15',
        location: 'Shenzhen warehouse, China',
        title: 'Shipment created',
        description: 'CargoSoon received the order and confirmed DDP service.',
      },
    ],
    orderInfo: {
      orderNumber: 'CSO-DDP-SEA-1001',
      incoterm: 'DDP',
      customerReference: 'REF-AMZ-LAX-1001',
      serviceLevel: 'Standard sea DDP',
      consignee: 'Amazon FBA - LAX9',
    },
    cargoInfo: {
      commodity: 'Home storage organizers',
      cartons: 86,
      grossWeight: '1,248 kg',
      volume: '7.6 CBM',
      destinationZip: '92376',
    },
    customs: {
      status: 'Export released',
      note: 'Import clearance will start after arrival notice.',
    },
    delivery: {
      status: 'Ocean transit',
      appointment: 'Pending final terminal release',
    },
    documents: [
      { name: 'Commercial Invoice', status: 'Ready' },
      { name: 'Packing List', status: 'Ready' },
      { name: 'Delivery Order', status: 'Pending' },
    ],
  },
  {
    id: 'cargosoon-air-ddp',
    source: 'cargosoon_order',
    numberType: 'cargosoon_order',
    searchKeys: ['CSO-DDP-AIR-2001', 'SHP-CANCHI-2001', 'REF-SHOPIFY-CHI-2001'],
    displayNumber: 'CSO-DDP-AIR-2001',
    shipmentNumber: 'SHP-CANCHI-2001',
    customerReference: 'REF-SHOPIFY-CHI-2001',
    status: 'air_transit',
    statusLabel: 'Air transit',
    carrier: 'CargoSoon Air DDP',
    service: 'Air DDP door-to-door',
    origin: 'Guangzhou, China',
    destination: 'Chicago, IL, United States',
    etd: 'Jun 15, 2026',
    eta: 'Jun 20, 2026',
    latestUpdate: 'Flight departed from Guangzhou. Import documents are under pre-check.',
    route: ['Guangzhou', 'Air export', 'Chicago', 'Local delivery'],
    events: [
      {
        time: 'Jun 16, 2026 08:15',
        location: 'Guangzhou Baiyun Airport',
        title: 'Flight departed',
        description: 'Airline has confirmed uplift from origin.',
      },
      {
        time: 'Jun 15, 2026 21:00',
        location: 'Guangzhou, China',
        title: 'Export scan completed',
        description: 'Shipment was accepted by the air export terminal.',
      },
      {
        time: 'Jun 14, 2026 13:20',
        location: 'CargoSoon Guangzhou hub',
        title: 'Cargo received',
        description: 'Cartons checked in and prepared for air DDP service.',
      },
    ],
    orderInfo: {
      orderNumber: 'CSO-DDP-AIR-2001',
      incoterm: 'DDP',
      customerReference: 'REF-SHOPIFY-CHI-2001',
      serviceLevel: 'Air DDP',
      consignee: 'Shopify warehouse - Chicago',
    },
    cargoInfo: {
      commodity: 'Phone accessories',
      cartons: 18,
      grossWeight: '212 kg',
      volume: '1.4 CBM',
      destinationZip: '60608',
    },
    customs: {
      status: 'Pre-check in progress',
      note: 'Broker is reviewing invoice and packing data.',
    },
    delivery: {
      status: 'Pending arrival',
      appointment: 'Delivery appointment opens after import release.',
    },
    documents: [
      { name: 'Air Export Manifest', status: 'Ready' },
      { name: 'Commercial Invoice', status: 'Ready' },
      { name: 'Proof of Delivery', status: 'Pending' },
    ],
  },
  {
    id: 'cargosoon-delivered',
    source: 'cargosoon_order',
    numberType: 'shipment_number',
    searchKeys: ['CSO-DELIVERED-3001', 'SHP-NYLON-3001', 'REF-WHS-NY-3001'],
    displayNumber: 'CSO-DELIVERED-3001',
    shipmentNumber: 'SHP-NYLON-3001',
    customerReference: 'REF-WHS-NY-3001',
    status: 'delivered',
    statusLabel: 'Delivered',
    carrier: 'CargoSoon DDP',
    service: 'Sea DDP warehouse delivery',
    origin: 'Ningbo, China',
    destination: 'New York, NY, United States',
    etd: 'May 3, 2026',
    eta: 'Jun 10, 2026',
    latestUpdate: 'Delivered and signed by warehouse receiving team.',
    route: ['Ningbo', 'New York', 'Final mile delivery'],
    events: [
      {
        time: 'Jun 12, 2026 14:05',
        location: 'New York, NY',
        title: 'Delivered',
        description: 'Shipment was signed by the consignee.',
      },
      {
        time: 'Jun 12, 2026 08:10',
        location: 'New York, NY',
        title: 'Out for delivery',
        description: 'Truck departed local terminal.',
      },
      {
        time: 'Jun 9, 2026 16:25',
        location: 'Newark, NJ',
        title: 'Import released',
        description: 'Customs clearance completed.',
      },
      {
        time: 'May 5, 2026 11:20',
        location: 'Ningbo Port, China',
        title: 'Vessel departed',
        description: 'Ocean leg started.',
      },
    ],
    orderInfo: {
      orderNumber: 'CSO-DELIVERED-3001',
      incoterm: 'DDP',
      customerReference: 'REF-WHS-NY-3001',
      serviceLevel: 'Sea DDP',
      consignee: 'NY retail warehouse',
    },
    cargoInfo: {
      commodity: 'Kitchenware',
      cartons: 42,
      grossWeight: '620 kg',
      volume: '4.1 CBM',
      destinationZip: '11232',
    },
    customs: {
      status: 'Released',
      note: 'Import clearance completed on Jun 9, 2026.',
    },
    delivery: {
      status: 'Delivered',
      appointment: 'Signed on Jun 12, 2026 at 14:05.',
    },
    documents: [
      { name: 'Proof of Delivery', status: 'Ready' },
      { name: 'Customs Release', status: 'Ready' },
      { name: 'Invoice Packet', status: 'Ready' },
    ],
  },
  {
    id: 'cargosoon-customs',
    source: 'cargosoon_order',
    numberType: 'customer_reference',
    searchKeys: ['CSO-CUSTOMS-4001', 'SHP-NGBEWR-4001', 'REF-FBA-EWR-4001'],
    displayNumber: 'CSO-CUSTOMS-4001',
    shipmentNumber: 'SHP-NGBEWR-4001',
    customerReference: 'REF-FBA-EWR-4001',
    status: 'customs_clearance',
    statusLabel: 'Customs clearance',
    carrier: 'CargoSoon Sea DDP',
    service: 'Sea DDP to Amazon FBA',
    origin: 'Ningbo, China',
    destination: 'Newark, NJ, United States',
    etd: 'May 18, 2026',
    eta: 'Jun 24, 2026',
    latestUpdate: 'Import clearance is in progress. Broker is reviewing entry data.',
    route: ['Ningbo', 'Newark', 'Customs', 'FBA delivery'],
    events: [
      {
        time: 'Jun 16, 2026 10:40',
        location: 'Newark, NJ',
        title: 'Customs entry in progress',
        description: 'Broker is processing import declaration.',
      },
      {
        time: 'Jun 15, 2026 07:50',
        location: 'Newark, NJ',
        title: 'Arrived at port',
        description: 'Container discharged from vessel.',
      },
      {
        time: 'May 20, 2026 12:30',
        location: 'Ningbo Port, China',
        title: 'Departed origin port',
        description: 'Ocean shipment is on schedule.',
      },
    ],
    orderInfo: {
      orderNumber: 'CSO-CUSTOMS-4001',
      incoterm: 'DDP',
      customerReference: 'REF-FBA-EWR-4001',
      serviceLevel: 'Sea DDP',
      consignee: 'Amazon FBA - EWR4',
    },
    cargoInfo: {
      commodity: 'Pet supplies',
      cartons: 64,
      grossWeight: '890 kg',
      volume: '5.2 CBM',
      destinationZip: '08691',
    },
    customs: {
      status: 'In progress',
      note: 'Entry data submitted. Release is subject to customs review.',
    },
    delivery: {
      status: 'Waiting for customs release',
      appointment: 'FBA appointment will be requested after terminal pickup.',
    },
    documents: [
      { name: 'Commercial Invoice', status: 'Ready' },
      { name: 'Packing List', status: 'Ready' },
      { name: 'Customs Release', status: 'Pending' },
    ],
  },
  {
    id: 'cargosoon-warehouse-processing',
    source: 'cargosoon_order',
    numberType: 'shipment_number',
    searchKeys: ['CSO-WH-5001', 'SHP-SZSEA-5001', 'REF-SEA-WH-5001'],
    displayNumber: 'CSO-WH-5001',
    shipmentNumber: 'SHP-SZSEA-5001',
    customerReference: 'REF-SEA-WH-5001',
    status: 'warehouse_processing',
    statusLabel: 'Warehouse processing',
    carrier: 'CargoSoon Warehouse',
    service: 'Consolidation before DDP shipping',
    origin: 'Shenzhen warehouse, China',
    destination: 'Seattle, WA, United States',
    etd: 'Jun 19, 2026',
    eta: 'Jul 18, 2026',
    latestUpdate: 'Warehouse team is checking cartons and preparing export labels.',
    route: ['Shenzhen warehouse', 'Export booking', 'Seattle', 'Door delivery'],
    events: [
      {
        time: 'Jun 16, 2026 11:10',
        location: 'Shenzhen warehouse, China',
        title: 'Warehouse processing',
        description: 'Carton count and label check are in progress.',
      },
      {
        time: 'Jun 15, 2026 17:35',
        location: 'Shenzhen warehouse, China',
        title: 'Cargo received',
        description: 'Supplier cartons arrived at CargoSoon warehouse.',
      },
      {
        time: 'Jun 15, 2026 09:00',
        location: 'CargoSoon system',
        title: 'Order created',
        description: 'Shipment plan opened for sea DDP service.',
      },
    ],
    orderInfo: {
      orderNumber: 'CSO-WH-5001',
      incoterm: 'DDP',
      customerReference: 'REF-SEA-WH-5001',
      serviceLevel: 'Sea DDP',
      consignee: 'Seattle 3PL warehouse',
    },
    cargoInfo: {
      commodity: 'Outdoor accessories',
      cartons: 37,
      grossWeight: '510 kg',
      volume: '3.8 CBM',
      destinationZip: '98108',
    },
    customs: {
      status: 'Not started',
      note: 'Customs documents will be prepared after warehouse confirmation.',
    },
    delivery: {
      status: 'Not started',
      appointment: 'Pending export booking.',
    },
    documents: [
      { name: 'Warehouse Receipt', status: 'Ready' },
      { name: 'Commercial Invoice', status: 'Pending review' },
      { name: 'Packing List', status: 'Pending review' },
    ],
  },
]

export const globalTrackingRecords = [
  {
    id: 'global-ups-style',
    source: 'global_express',
    numberType: 'express',
    searchKeys: ['1Z999AA10123456784'],
    displayNumber: '1Z999AA10123456784',
    status: 'in_transit',
    statusLabel: 'In transit',
    carrier: 'UPS style express',
    service: 'International express',
    origin: 'Ontario, CA, United States',
    destination: 'Dallas, TX, United States',
    etd: 'Jun 14, 2026',
    eta: 'Jun 18, 2026',
    latestUpdate: 'Package departed regional sorting facility.',
    route: ['Ontario', 'Dallas', 'Delivery'],
    events: [
      {
        time: 'Jun 16, 2026 06:45',
        location: 'Phoenix, AZ',
        title: 'Departed facility',
        description: 'Package is moving through the carrier network.',
      },
      {
        time: 'Jun 15, 2026 19:10',
        location: 'Ontario, CA',
        title: 'Origin scan',
        description: 'Carrier received the package.',
      },
    ],
  },
  {
    id: 'global-container',
    source: 'container',
    numberType: 'container',
    searchKeys: ['MSKU1234567'],
    displayNumber: 'MSKU1234567',
    status: 'on_vessel',
    statusLabel: 'On vessel',
    carrier: 'Maersk style container tracking',
    service: 'Ocean container',
    origin: 'Yantian, China',
    destination: 'Long Beach, CA, United States',
    etd: 'Jun 10, 2026',
    eta: 'Jul 2, 2026',
    latestUpdate: 'Container loaded on vessel and departed origin port.',
    route: ['Yantian', 'Pacific Ocean', 'Long Beach'],
    events: [
      {
        time: 'Jun 12, 2026 23:30',
        location: 'Yantian Port, China',
        title: 'Vessel departed',
        description: 'Container is on the ocean leg.',
      },
      {
        time: 'Jun 10, 2026 16:20',
        location: 'Yantian Port, China',
        title: 'Loaded on vessel',
        description: 'Container was loaded at origin terminal.',
      },
      {
        time: 'Jun 9, 2026 09:15',
        location: 'Yantian Port, China',
        title: 'Gate in',
        description: 'Container entered terminal.',
      },
    ],
  },
  {
    id: 'global-ocean-bl',
    source: 'ocean_bl',
    numberType: 'ocean_bl',
    searchKeys: ['COSU1234567890', 'COSU 1234567890'],
    displayNumber: 'COSU1234567890',
    status: 'port_arrival',
    statusLabel: 'Port arrival',
    carrier: 'COSCO style ocean carrier',
    service: 'Ocean B/L tracking',
    origin: 'Shanghai, China',
    destination: 'Oakland, CA, United States',
    etd: 'May 29, 2026',
    eta: 'Jun 17, 2026',
    latestUpdate: 'Vessel arrived at destination port. Discharge is pending.',
    route: ['Shanghai', 'Oakland'],
    events: [
      {
        time: 'Jun 16, 2026 05:20',
        location: 'Oakland, CA',
        title: 'Arrived at destination port',
        description: 'Vessel arrival has been confirmed.',
      },
      {
        time: 'May 31, 2026 14:00',
        location: 'Shanghai, China',
        title: 'Vessel departed',
        description: 'Ocean transit started.',
      },
      {
        time: 'May 29, 2026 10:25',
        location: 'Shanghai, China',
        title: 'B/L created',
        description: 'Carrier accepted shipping instructions.',
      },
    ],
  },
  {
    id: 'global-air-awb',
    source: 'air_awb',
    numberType: 'air_awb',
    searchKeys: ['784-12345675', '78412345675'],
    displayNumber: '784-12345675',
    status: 'departed_origin',
    statusLabel: 'Departed origin',
    carrier: 'Air cargo carrier',
    service: 'Air waybill tracking',
    origin: 'Hong Kong, China',
    destination: 'Los Angeles, CA, United States',
    etd: 'Jun 16, 2026',
    eta: 'Jun 17, 2026',
    latestUpdate: 'Shipment departed origin airport.',
    route: ['Hong Kong', 'Los Angeles'],
    events: [
      {
        time: 'Jun 16, 2026 12:05',
        location: 'Hong Kong International Airport',
        title: 'Departed origin airport',
        description: 'Flight departure has been confirmed.',
      },
      {
        time: 'Jun 16, 2026 07:40',
        location: 'Hong Kong International Airport',
        title: 'Accepted by airline',
        description: 'Cargo accepted under air waybill.',
      },
    ],
  },
  {
    id: 'global-partner-order',
    source: 'partner_order',
    numberType: 'partner_order',
    searchKeys: ['3PL-ORDER-889900', 'FWD-US-2026-7788', 'LSP-SZX-LAX-2026'],
    displayNumber: '3PL-ORDER-889900',
    status: 'handover_received',
    statusLabel: 'Handover received',
    carrier: 'Partner logistics system',
    service: 'Third-party logistics order tracking',
    origin: 'Shenzhen, China',
    destination: 'Los Angeles, CA, United States',
    etd: 'Jun 18, 2026',
    eta: 'Jul 12, 2026',
    latestUpdate:
      'The partner logistics provider has received the shipment and shared the latest handover event.',
    route: ['Shenzhen', 'Partner hub', 'Los Angeles'],
    events: [
      {
        time: 'Jun 16, 2026 15:35',
        location: 'Shenzhen partner hub',
        title: 'Handover received',
        description: 'Shipment was received under the partner logistics order ID.',
      },
      {
        time: 'Jun 16, 2026 10:10',
        location: 'Supplier warehouse, China',
        title: 'Pickup completed',
        description: 'Partner carrier collected the cartons from supplier warehouse.',
      },
      {
        time: 'Jun 15, 2026 18:00',
        location: 'Partner logistics system',
        title: 'Order created',
        description: 'Third-party logistics order was created and is waiting for pickup.',
      },
    ],
  },
  {
    id: 'global-delivered',
    source: 'global_express',
    numberType: 'express',
    searchKeys: ['DHLDELIVERED2026'],
    displayNumber: 'DHLDELIVERED2026',
    status: 'delivered',
    statusLabel: 'Delivered',
    carrier: 'DHL style express',
    service: 'International express',
    origin: 'Cincinnati, OH, United States',
    destination: 'Miami, FL, United States',
    etd: 'Jun 11, 2026',
    eta: 'Jun 13, 2026',
    latestUpdate: 'Shipment delivered to recipient.',
    route: ['Cincinnati', 'Miami'],
    events: [
      {
        time: 'Jun 13, 2026 11:25',
        location: 'Miami, FL',
        title: 'Delivered',
        description: 'Signed by receiving desk.',
      },
      {
        time: 'Jun 13, 2026 08:05',
        location: 'Miami, FL',
        title: 'Out for delivery',
        description: 'Courier is completing final delivery.',
      },
      {
        time: 'Jun 11, 2026 18:15',
        location: 'Cincinnati, OH',
        title: 'Processed at facility',
        description: 'Shipment entered the express network.',
      },
    ],
  },
]
